sudo: required
services:
  - docker

before_install:
  - docker build -t uday3110/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true uday3110/docker-react npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_path: "docker"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on:
    branch: master
